### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by XRIICrypto** [Legedric/ptmagic#10]
<img width="635" alt="schermafbeelding 2018-02-17 om 14 49 17" src="https://user-images.githubusercontent.com/33671425/36341728-0aa0cc60-13f3-11e8-8a70-3749b56658e3.png">

Tried to use PTMagic also for my Binance. Monitor works here but the bot spits out this message.

**Comment by XRIICrypto** [comment]
FYI: ETH market on Binance. Market trends spits out information for BTC pair while I'm using ETH.

**Comment by Legedric** [comment]
I will try to recreate this issue and look into this error. Thanks for posting the issue!

**Comment by Legedric** [comment]
Hi @XRIICrypto!

So I tried to reproduce your issue but for me the bot is running fine with ETH on Binance.

Did you run the bot at first with BTC?
If so, please delete the content of your "_data" directory AND make sure that you changed the "MARKET = ETH" in your pairs properties in your Profit Trailer/traing folder AND in your _presets of PT Magic. Otherwise the bot will take the "old" entry for "MARKET = ".

**Comment by calebcall** [comment]
I don't have the above error, but mine is also showing BTC for my bot that's trading in ETH as the base pair.  I have confirmed I do have MARKET = ETH in my pairs files in my PT folder as well as in the _presets/Default/PAIRS.properties file in my PTMagic directory.  The values all dow ETH but the wording is BTC, see attached screenshot (I wish it was back when BTC was still $900 USD)

![screen shot 2018-02-18 at 6 29 35 pm](https://user-images.githubusercontent.com/1132262/36359758-548a52fe-14db-11e8-8b22-12f118ea22f4.png)

**Comment by Legedric** [comment]
@calebcall Thanks for posting this, the header showing BTC is indeed a bug.
