### ISSUE TITLE
maintaining changes to pairs.properties twice

### ISSUE THREAD

**Issue by jsnx** [Legedric/ptmagic#171]
According to the wiki you have to make changes to the pairs.properties in the profit trailer folder "./trading/" and also in the ptmagic folder "./_presets/Default/

> "If you want to change some settings for Profit Trailer while PT Magic is running make sure you change them in 2 files."

Thats not very handy. 

Proposal:
a.) integrate a form to the monitor that lets you change the values in "./_presets/Default/pairs.properties" and write them to "./trading/pairs.properties" as well after hitting a save button

or

b.) get rid of the presets and recognize changes made by the user and ptmagic (meaning: delete old changes from ptmagic in the pairs.properties before writing new one into it)

**Comment by bvebve** [comment]
On previous versions I only have to update presets *.properties. PTM was getting those files, transforming them and writing the new *.properties to PT's trading folder.
With version 1.1.1 i'm having [issues](https://github.com/Legedric/ptmagic/issues/172).

**Comment by HojouFotytu** [comment]
@bvebve I believe this only happens if you change a setting that is currently controlled by analyzer.    Iif you make a change to a setting in pairs that isn't currently being monitored/generated by analyzer, it acknowledges the change, but doesn't see a need to write a new settings file.

@jsnx I like proposal "A"  In fact, I mentioned the exact same thing in chat the other day.  I currently keep two editing windows open, so I can make quick changes that I don't want to analyzer to overwrite if it changes settings.   An addition to the monitor that allows you to edit the default settings (similar to PT config) which force PTM to generate a new settings file on save.

It's not a huge problem, but it is one of the biggest choke-points and distractions in my work-flow when trading and using the bot.  I'm guessing most users are like me, and don't just turn it on and let it go, but do a lot of hands-on settings management while trading.  

Anyway, one way to simplify the current situation and conserve desktop space, is to use chrome developer mode so you can keep the two files side-by-side.    In chrome you can edit a local file and ctrl+s to save it...
![image](https://user-images.githubusercontent.com/36724681/36625384-f33d6a5a-1961-11e8-9bdf-045953482b3e.png)

**Comment by JeanGalt** [comment]
If I may, I think it's not a good idea for PTMagic to write anything in PT's directories.
In the event of PT malfunctions, this could result in unwarranted liability to the PTMagic authors.

**Comment by HojouFotytu** [comment]
@JeanGalt um, that's basically the entire point of the software.  I think you don't understand how it works?

**Comment by JeanGalt** [comment]
oooops .... ooooops ....
Promised, next time I will think a little more before writing nonsense !

**Comment by goferit** [comment]
+1

Right now I shut down both PT and PTM every time I make a settings change. I make a change to the PT folder file, save it, then save it again in the PTM folder. This has to be the absolute worse way to do it, and probably not the only option, but changing settings in one place is a no brainer, and the Monitor is much more elegant than the .properties files + Notepad++.

**Comment by Legedric** [comment]
You do not have to shutdown PT or PTM for setting changes. They applied the changes on the fly.

**Comment by Tosko4** [comment]
@jsnx I love your A proposal. I hope the developers will listen to this.

**Comment by securitygeneration** [comment]
@Legedric I think this is similar to what we just chatted about. Instead of having to update PT properties files as well as the _presets/Default properties for PTM, it would be nice to be able to make the config changes within PTM UI (i.e. via similar GUI file editor of preset files) and then PTM simply pushing the updates to the PT files upon save (instead of waiting for market change).

If users know that when using PTM, the 'source of truth' for the properties files will now always be the PTM presets, then it makes it clear which files should be updated.

When updating the PT properties files, you could even include a comment that says:

`This file in now managed by PT Magic. In order to make manual changes to this file, please make them within _presets/Default/<file>.`

#323 is also related to this ticket.

**Comment by mightysoul** [comment]
+1 for me,

It would be handy at least to change the default files from PTM GUI. You don't need to  overwrite on the PT files. Currenty I need to ssh then change the PTM default file , then I change the PT file as well. Doing these things from GUI is making it much more convenient.

**Comment by Legedric** [comment]
I think this should no longer necessary as PTM now automatically reapplies the current settings as soon as you change your files located in _presets.
