### ISSUE TITLE
ERRORS ON BTC , ETH , USDT BOTS

### ISSUE THREAD

**Issue by mfcholdings** [Legedric/ptmagic#187]
![btc error](https://user-images.githubusercontent.com/36377757/36630542-8283a50c-1968-11e8-89fd-b3404e7d2ff6.png)
![eth error](https://user-images.githubusercontent.com/36377757/36630543-8298dfbc-1968-11e8-8263-529f090718a1.png)
![usdt error](https://user-images.githubusercontent.com/36377757/36630544-82abfe9e-1968-11e8-966a-0c974e5093db.png)

USDT NOT SHOWING PRICE...  
ETH GETS ERROR 
BTC GETS ERROR

**Comment by mfcholdings** [comment]
Any help with these errors

**Comment by alexpica** [comment]
Code 429, as specified in the official Binance API doc, is used for surpassing the request limit. 
See here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md 

This should be throttled by devs in the code, not sure you can do anything...

Do you use the same API key for other stuff as well?

**Comment by Legedric** [comment]
The thing is, PT magic does 1 (yes, ONE) request per minute to Binance. So it is impossible that PT magic is responsible for reaching your Binance API limit (which is 1200 request per minute).

Maybe it is because you are running multiple bots from the same API Key/machine on Binance but it is not related to PT Magic.
