### ISSUE TITLE
Request : A way to wipe PT histories without to lose them with PTMagic

### ISSUE THREAD

**Issue by JeanGalt** [Legedric/ptmagic#188]
PTMagic allows to do very goods statistics with PT history.
But this makes it necessary to lengthen the duration of this history and to slow down the display of the web pages of the PT server.
Could PTMagic store these logs in addition to its own, in order to clean up PT without losing anything?

**Comment by Legedric** [comment]
At the moment I do not know of any reports that PT itself is getting slow because of large Sales Logs or ProfitTrailerData.json files (that is where PT stores its data).
I tested it even myself with a Sales log with more than 10k entries and everything was working extremely fine and fast for me.

So I do not see any need of developing some kind of backup method from PT to PT Magic.

**Comment by JeanGalt** [comment]
Keeping the history from the beginning, after 1 month of PT I have a ProfitTrailerData.json file of about 300 KB (with about 400 sales orders).
Compared to a new configuration, I see a slight slowdown in the display of the Sales Log page, perhaps because of the fact that PT is installed on another machine of my wifi network.
This slight slowdown is not a problem at the moment, in any case much less than the ProfitTrailer.log file (about 6 MB and 38000 lines), which I use to retrieve order details in Excel.
But as I intend to continue to use PT for as long as possible, I was wondering if the size of these files could not end up becoming a problem.

**Comment by Legedric** [comment]
Sorry but PT Magic is not there to compensate Profit Trailer not being able to load sales log at a decent speed. That's for Profit Trailer to improve.

**Comment by JeanGalt** [comment]
Yes.
