### ISSUE TITLE
RFE - Greater verbosity on issues prior to core-dump

### ISSUE THREAD

**Issue by jeffcpullen** [Legedric/ptmagic#193]
I've run into this issue twice where I made some change and it is extremely difficult to troubleshoot where the issue is. The first time it was an issue with filetype that a dos2unix was able to correct. It is hard to tell if this is a json formatting issue like a missing comma, a file access issue, or what.

It reports that 'Sequence contains no elements'

Would it be possible to identify what sequence that is?

```Feb 24 13:25:55 profittrailer.example.com ptmagic[5005]: 2018/02/24 13:25:55.216 INFO - Exchange - 0 Market trend changes built for 'Exchange12h'.

Feb 24 13:25:55 profittrailer.example.com ptmagic[5005]: 2018/02/24 13:25:55.217 INFO - Exchange - Building market trend changes for 'Exchange24h' on main market 'ETH' with 1 markets...

Feb 24 13:25:55 profittrailer.example.com ptmagic[5005]: 2018/02/24 13:25:55.227 INFO - Exchange - 0 Market trend changes built for 'Exchange24h'.

Feb 24 13:25:55 profittrailer.example.com ptmagic[5005]: 2018/02/24 13:25:55.227 INFO - Checking single market settings triggers for 1 markets...

Feb 24 13:25:55 profittrailer.example.com ptmagic[5005]: Unhandled Exception: System.InvalidOperationException: Sequence contains no elements

Feb 24 13:25:55 profittrailer.example.com ptmagic[5005]:    at System.Linq.Enumerable.Average[TSource](IEnumerable`1 source, Func`2 selector)

Feb 24 13:25:55 profittrailer.example.com ptmagic[5005]:    at PTMagic.PTMagic.MarketTrendCheckTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\Tools\PTMagic\PTMagic\PTMagic.cs:line 393

Feb 24 13:25:55 profittrailer.example.com ptmagic[5005]:    at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 177

Feb 24 13:25:55 profittrailer.example.com systemd[1]: ptmagic.service: Main process exited, code=dumped, status=6/ABRT

Feb 24 13:25:55 profittrailer.example.com systemd[1]: ptmagic.service: Unit entered failed state.

Feb 24 13:25:55 profittrailer.example.com systemd[1]: ptmagic.service: Failed with result 'core-dump'.```

**Comment by Legedric** [comment]
Please follow these steps:
- Stop PT Magic
- Delete the folder "Exchange" in "_data" in PT Magic
- Start PT Magic (It will take up to 15 minutes as it will rebuild the data)

**Comment by jeffcpullen** [comment]
@Legedric Thanks for the feedback. I did try that and let it rebuild and got the same result.

**Comment by Legedric** [comment]
Is the error still occuring after some time?

**Comment by jeffcpullen** [comment]
I tried the last several versions with the same result.

Closing this since I don't have the time to isolate the issue enough to continue troubleshooting this particular issue. I'll try and replicate it later this week and will open a new issue if it continues. Thanks.

**Comment by tomthedude** [comment]
i had this issue with ptmagic, i did chmod -R 777 to all the folder and then the proccess started succesfully, i am sure it is not the best solution but it's a clue.
also ptmagic-monitor did not start for me, after chmod it started, but then after reboot, i can start ptmagic fine, but ptmagic-monitor gives me core-dump:
 Active: failed (Result: core-dump) since Mon 2018-05-07 00:31:26 IDT; 2min 13s ago
  Process: 2674 ExecStart=/usr/bin/dotnet Monitor/Monitor.dll (code=dumped, signal=ABRT)



it's really wierd... since ptmagic is running ok on the same core..



May 07 00:31:26  ptmagic-monitor[2674]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Thr
May 07 00:31:26  ptmagic-monitor[2674]:    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Config
May 07 00:31:26 ptmagic-monitor[2674]:    at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesS
May 07 00:31:26 ptmagic-monitor[2674]:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplica
May 07 00:31:26 ptmagic-monitor[2674]:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
May 07 00:31:26 ptmagic-monitor[2674]:    at Monitor.Program.BuildWebHost(String[] args, String content
May 07 00:31:26 ptmagic-monitor[2674]:    at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Mo
May 07 00:31:26 systemd[1]: ptmagic-monitor.service: Main process exited, code=dumped, status=6/ABRT
May 07 00:31:26 systemd[1]: ptmagic-monitor.service: Unit entered failed state.
May 07 00:31:26 systemd[1]: ptmagic-monitor.service: Failed with result 'core-dump'.
