### ISSUE TITLE
[Community] Accept Crypto Crow's YT Interview Invite

### ISSUE THREAD

**Issue by goferit** [Legedric/ptmagic#245]
@Legedric You've been invited to dispel the myths, brother!

https://youtu.be/X2K8a7ntGpg?t=20m7s

This is large healthy community that would benefit from PTM.

**Comment by Legedric** [comment]
We never capproached anyone so far to interview us or promote/endorse our project.

Anyone we talked to or chatted with so far approached us as they wanted to know something from us, no matter if it was Crypto Face, CryptoGnome or Elroy (the lead developer of PT) when he wanted a code walkthrough of PT Magic.

So if anyone wants to interview me to talk about our project, our intentions etc. they may contact me anytime directly on Discord, Youtube or here on GitHub and we will find a spot for a meeting.
But we won't go and contact anyone upfront asking for attention to justify ourselves.

**Comment by Tosko4** [comment]
And Legedric has already given an interview.

**Comment by HojouFotytu** [comment]
Crypto Crow is the same guy that posted all over his disocord  "DO NOT USE PTmagic!  It is a scam!  It will steal your API keys!  You've been warned!"  when he first realized there a free product threatening his feeder-affiliate revenue stream.  ;)

**Comment by goferit** [comment]
@Tosko4 That's like saying "Legedric's already released a version of PTM". Life is emergent, and iterative.

Posted a link to this issue back on the vid, ball's in their court!

**Comment by Tosko4** [comment]
@goferit I understand what you are saying. Don’t get me wrong. It’s just that it has been quite unfair, all the attacks on PT Magic. 

There are so many free tools out there without any sell strategy behind it. I am glad these two guys are working on the code and help us all out that don’t have a large wallet to keep buying products such as Feeder. 

Also, it’s insane. So many people want to talk to Legedric. So many youtubers asked for an interview. He’s just going to end up answering most of the same questions. That Crypto Crow could also link his audience to the vid where they do the interview. It’s just a little drama and he wants to post vids for his own personal gain. 

It’s either, use the product or not. It’s not that they are earning off of you. And I would very much prefer Legedric and his partner to focus on the scripting part and keep improving this lovely product, instead of doing PR and Marketing stuff.

**Comment by goferit** [comment]
@Tosko4 That's a good point, about where the information gets put, and the economic incentive behind it. I was only thinking about the objective of getting the information out to the community. And I agree, this has damaged the credibility of some parties, while others have retracted their initial overzealous statements. And none of it has been fair to the developer, nor do I think serious people have taken it seriously. At all.

To return to your point, creating a contentious topic where there is none, to draw eyeballs and affiliate link clickers, to then invite the developer to set the record straight on a now popular topic, to draw more eyeballs and affiliate link clickers, may not be what's happening at all (and to be clear, I am not making the claim that it is, only that such a conflict might exist), and if the true objective is to help the community, linking to the information, wherever it is, if it is already available, to dispel those myths, is a path less riddled with potential conflicts of interest.

And if the information is unavailable, it would benefit the community to access it, wherever it is. I assume Cryptoface, I did not watch it, too busy playing with PTM and bulletproofing PT from P&Ds!

Thanks for your comment.
