### ISSUE TITLE
PTMagic Monitor does not startup

### ISSUE THREAD

**Issue by BokHolders** [Legedric/ptmagic#275]
![image](https://user-images.githubusercontent.com/37026226/36938361-a88e16a2-1f20-11e8-8ea4-776cf4d37314.png)
![image](https://user-images.githubusercontent.com/37026226/36938429-c11f76c4-1f21-11e8-9cec-f89b58fe0882.png)

Hi, I've installed the new Windows .Net Core Runtime 2.05 and the ASP.NET core runtime through: 

However the monitor does not start up whether I've installed either or both of the programs, giving different errors. This is the error if I install both. Can you help me out? Good luck with all the nice magic work!

**Comment by Legedric** [comment]
1. The runtime packages are not enough, you need to download the Windows Hosting package as described in our wiki:
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

2. You seem to have invalidated your appsettings.json file in your Monitor folder when you entered the path there. Please use this JSon validator to see what the issue is or what you did wrong there:
https://jsonlint.com

**Comment by BokHolders** [comment]
Dear Legedric,

Thank you for your quick respons! Thanks to your help, I was able to fix it and get the monitor running! The problem was a missing backlash '/' in the path in the appsettings.json file in the Monitor folder. So this was point 2. 

Suggestion about point 1:
Please note that the windows website is recently updated and therefore the instructions on the wiki looks outdated. Maybe people like me have difficulties downloading the right file now. I think it would be nice to update the screenshots. :-)

**Comment by Legedric** [comment]
Thanks, any feedback is much appreciated!
