### ISSUE TITLE
[Bug] Sorting on Market Trends page

### ISSUE THREAD

**Issue by HojouFotytu** [Legedric/ptmagic#290]
Not a biggie, but on my Market Trends page, only "Market Name", and the first two out of six trends are sortable.  Clicking on the title of the other trends does nothing.  

I thought maybe the short names ("1h", "12h") or too many trends (I have 6) but i tried playing around with the names and number of trends and it didn't fix it.

**Comment by Legedric** [comment]
That isssue is already fixed in the upcoming release. The sort function is broken in that case because a new coin may have got introduced to your exchange and has no trend for 24h and upwards so.
Please check your Trends page and see if you can confirm that there is a coin that has no data in 24h and larger trends. If so, it is the same issue.

**Comment by HojouFotytu** [comment]
Ah yeah.  there is a coin without those trends.  Thanks!
