### ISSUE TITLE
Total Gain % cannot be calculated because of manual transactions?

### ISSUE THREAD

**Issue by Fransenson** [Legedric/ptmagic#303]
I was looking forward to the manual transaction feature as I thought it would bring a more correct estimation for my gains.

Now I wonder why this is:

![bildschirmfoto 2018-03-12 um 09 24 32](https://user-images.githubusercontent.com/5176886/37272576-51e6bada-25d7-11e8-993a-5ba9e174592b.png)

I added 3 transactions that happened in the past after updating to 1.3.0. Before 1.3.0 I just added them to my starting balance. Now I went back to my original starting balance and added the deposits to transactions.

**Comment by Legedric** [comment]
Pretty simple:
Your total gain is usually being calculated using your starting balance like this:
`TotalGain = TotalProfit / StartingBalance /100`

 But when you add transactions (either way) to it, the total gain using this formula would be way off because the profits you accumulate with your new balance (after a deposit for example) may be way higher than the profits you had with your starting balance.

**Comment by Fransenson** [comment]
Thanks for the heads up!

**Comment by Fransenson** [comment]
@Legedric Sorry for getting this up again but I tried to to some math and I think you could incorporate deposits and withdrawals to your total gain function. 

I just did like so:

`TotalGain = TotalProfit / (StartBalance + Deposits - Withdrawals) /100`

And I figured that no matter how I turn the sheet, the TotalGain will be the same, with or without deposits / withdrawals. Screenshot of my table to look at:

![bildschirmfoto 2018-03-13 um 00 06 26](https://user-images.githubusercontent.com/5176886/37314069-66a96b2c-2652-11e8-9b94-a2e875f611eb.png)

If I took a wrong turn thinking about this please let me know. Otherwise I'd love to see this change in PTM.

**Comment by smoochy** [comment]
Removing the ability to display the total gain percentage kind of defeats the purpose of being able to add deposits and transactions. Of course I want to know, even with those 2 possible balance changes, my complete gain in %.

I am not very good at math, so please correct my naive thinking: but would it not be possible to do sth like this:

Lets say my starting balance is 3.127494 ETH.
I started on the 8th of March.
Made 0.02395840 ETH profit until 12th of March which results in a total of 0.77% gain.

On 12th of March I deposited 0.01659218 ETH at 22.58pm.

Would it not be possible to change the formula for TotalGain to:

TotalGainUpToDeposit1 = TotalProfitUpToDeposit1 / StartingBalance /100

TotalGainTotal = TotalProfitSinceDeposit1+TotalProfitUpToDeposit1 / TotalGainUpToDeposit1+StartingBalance  /100

Maybe I am not expressing myself correctly. If you want to, we could have a private chat on Discord in German.

In addition, I do have access to a Google Spreadsheet, which does take deposits and withdraws into consideration when calculating the total profit and its percentage. I could provide that to you, so you could have a look at it?

Thanks again for all your efforts.

**Comment by Legedric** [comment]
Guys, your math may seems correct but the result is not accurate.

![image](https://user-images.githubusercontent.com/8308141/37323412-fdb33fbc-2683-11e8-98bd-4e5c8ca043f1.png)

Let's assume you have a starting balance of 100 and you made a profit of 1 on your very first day.
- This results in a total gain of 1%

That's a solid and accurate result, no problems here without any transactions in between.

Now you have day 2 and you make no sales (so your profit is still at 1) but you deposit 50 units into your account. Although your profit did not change:
- Your new total gain will be 0.67% JUST because you deposited something into your account.

So your total gain is already off by a good chunk and useless.

On day 3, you withdraw 100 units and you still have no more sales and your total profit is still siting at 1:
- The total gain shown on day 3 after the withdraw is now 2%

So again your profit did not change, neither did your starting balance but your total gain is all over the place because of the transactions. No matter on how you move forward with this on a daily basis your **Total Gain will be off and inaccurate** after you made any transaction.
So please understand that we will not show any confusing and inaccurate numbers on our monitor just to show any number.

@smoochy 
Accumulating the total gains over the periods will also lead to a result that is way off:
![image](https://user-images.githubusercontent.com/8308141/37323513-8fa195e0-2684-11e8-9ac7-c4ebb2f6f048.png)

So in this example your gain on each of thise days individually is 1% but when you accumulate it the total gain would be 3% and that's of course wrong.

Of course you may point me to the spreadsheet but I doubt that their numbers are anything near accurate...

**Comment by smoochy** [comment]
Thank you for explaining this in detail and taking the time for that.

As we discussed already via Discord, you pointed out my imprecise thinking.
