### ISSUE TITLE
Lotsa logins!

### ISSUE THREAD

**Issue by CazBryant4** [Legedric/ptmagic#319]
<img width="1431" alt="screen shot 2018-03-15 at 2 18 30 pm" src="https://user-images.githubusercontent.com/36281320/37491772-1adb184c-285c-11e8-8dfb-ebbf8fc5da04.png">

Not sure if you can see this 'double login'. reloading the page fixes it
I get this always. 6 to 10 times daily.
Wondering why so often?
Could this be user adjustable?

**Comment by Legedric** [comment]
Usually the session timeout is set to 15 minutes.
But if you keep the monitor open it should never expire due to the refreshing top bar and/or dashbaord. However, that may differ depending on your machine's configuration which PTM has no influence on.

The "issue" that there are two login screens visible is occuring because the top bar ticket will return the legin as well instead of the ticket when your session expired.

**Comment by CazBryant4** [comment]
Aha - I thought the double login might be because I am running two instances.

Love your creation!




On Mar 15, 2018, at 9:14 PM, Legedric <notifications@github.com> wrote:

Usually the session timeout is set to 15 minutes.
But if you keep the monitor open it should never expire due to the refreshing top bar and/or dashbaord. However, that may differ depending on your machine's configuration which PTM has no influence on.

The "issue" that there are two login screens visible is occuring because the top bar ticket will return the legin as well instead of the ticket when your session expired.
