### ISSUE TITLE
Automatic calculation ALL_max_cost value on the basis of various parameters.

### ISSUE THREAD

**Issue by BaGRoS** [Legedric/ptmagic#331]
Many of us would like to trade using the force of a compound interest rate. Unfortunately, at this moment neither PT nor PTM support such a possibility.
My proposal is that the value of ALL_max_cost can be calculated at fixed intervals or every fixed number of transactions, or every fixed amount of money earned, or at fixed times every day.
ALL_max_cost = BALANCE / ALL_max_trading_pairs * DCA_max_buy_times
of course, the formula is not true because it would have to be ALL_max_cost on the right, but it should be understandable.

example
1. If BALANCE grows by 0.001BTC / $20 then calculate ALL_max_cost so that I can buy ALL_max_trading_pairs = 4 and DCA_max_buy_times = 2.

2. Calculate ALL_max_cost every day at 00:00 so that I can buy ALL_max_trading_pairs = 4 and DCA_max_buy_times = 2.

I know that we can set a percentage purchase, but it does not include pairs, or the amount of DCA levels. So if we change any of these values, we may not have enough money to cover the DCA.
We can think of the "CALCULATE ALL_max_cost" function when it detects a change in the number of pairs or DCA levels.

**Comment by Legedric** [comment]
I do not really see a point here. Because when you already go to your settings to change your numer of pairs and/or DCA levels you could directly recalculate and apply your new max_cost as well.

Yes, PTM could save the recalculation but it would add another level of complexity just for a single setting (max_cost/initial_cost) and generate another source of possible errors.

So I am afraid, but this will not get implemented into PTM.
