### ISSUE TITLE
[Feature: Single Market Settings] Market Signals - Trend Relative to Market All Time High (ATH)

### ISSUE THREAD

**Issue by goferit** [Legedric/ptmagic#348]
See screen capture from RHC of onchainfx.com.

![image](https://user-images.githubusercontent.com/8900109/37709292-2badd14a-2ce0-11e8-98c9-0510cc8f6ae5.png)

**Comment by Legedric** [comment]
Sorry, not gonna happen. The symbols on your exchange (so what you are actually trading) often do not match the symbols of globalized platforms like CMC or OCFX.

Furthermore I do not see a real use for this in PTM as PTM builds trends for single coins based on your market against BTC/ETH and USDT. So how could the ATH in USDT be of any nterest for me?
Especially when you consider market situations like right now where we are like wayyyyy below the ATH (since December 2017/January 2018) for months now.
