### ISSUE TITLE
Remember Me feature

### ISSUE THREAD

**Issue by securitygeneration** [Legedric/ptmagic#354]
At the moment you seem to have to re-authenticate to PTM quite often. It would be nice to have a 'remember me for a week' feature that sets a longer session timeout.

**Comment by HojouFotytu** [comment]
Seconded.  It's really annoying on my phone, since it seems to ask almost everytime i bring the browser app into focus, even if i never close it or navigate away from the page. Using a randomly generated 16 character password, it means i have to open my password manager and copy the password everytime i want to take a quick glance at PTM.

**Comment by securitygeneration** [comment]
It happens to me without fail on my phone if I've left it for a while (i.e. an hour).
