### ISSUE TITLE
[Feature Request] Control Panel

### ISSUE THREAD

**Issue by cybermizrach** [Legedric/ptmagic#379]
Can we have a  Control Panel with the following features?

**General Settings**
- Ability to define the all_max_cost, number of pairs, SOM, min/max volume, max spread, panic sell, and other PT settings.

**Coin Control Panel**
- Ability to enable/disable each coin for trading. This overrides whatever PT Magic setting has applied to a coin. 
- Ability to see the applied market setting(s)
- Ability to define PT settings and/or Saved Setting(including the SMS) to a coin.
- Ability to specify the allowed min volume & max volume for trading.

**Coin Grouping**
- Ability to create coin groups which each group has its own PT settings. 
- Each group can have an option to enable/disable trading, DCA, SOM to all coins under this group.
- Ability to assign coins in a group(s) which applies the PT settings assigned to the group.

**Saved Settings**
- Ability to create pre-defined PT settings including DCA which can be applied to a group or coin.

**Comment by Legedric** [comment]
I doubt that anything of the above mentioned topics will find its way into PTM.
The reason is that most of these things are more like directly adjusting PT's setting based off of nothing else but manual editing and this can AND should always be done with Profit Trailer itself, not with an addon which has the main purpose of adjusting settings automatically based on whatever triggers.
