### ISSUE TITLE
Enhancement: MinPairBagHours / MaxPairBagHours

### ISSUE THREAD

**Issue by ghost** [Legedric/ptmagic#440]
I'm doing charting based on 1-hour candles. The tendency is to hold a pair for days, but seek high returns (e.g., hold for 48 hours for 8% return). Request the ability to set a SMS if a pair is held for a certain amount of time. For example:

  {
    "SettingName": "Pair Long Hold Time",
    "StopProcessWhenTriggered": false,
    "TriggerConnection": "OR",
    "Triggers": [
      {
        "MinPairBagHours": 48.00
      }
    ],
    "PairsProperties": {
      "ALL_sell_value_OFFSETPERCENT": -50
    }

**Comment by Legedric** [comment]
The main problem with this is that PT itself only stores the time of the last buy order. So PTM is not able to get the full age of a bag as PT simply does not save that data.
PTM would only be able to track the age since the last buy time.

**Comment by Legedric** [comment]
What you see in PT Tracker is the tiem of the last buy. As long as a pair is not DCAd it is the initial buy time. But after the first DCA buy it is the time of THAT buy and no longer the initial one. Same applies if it goes into DCA 2, 3 and so on.
And no, PTM will not do its own data handling for those kind of things, meaning we will not implement something that separately stores the dates for initial buy, DCA 1, 2, 3 etc. Because as soon as this gets lost, deleted or corrupted for whatever reason there is no way to rebuild that as there is no kind of history of that stored in PT itself.
