### ISSUE TITLE
[Feature Request]Setting single market settings based off of indicators

### ISSUE THREAD

**Issue by Fransenson** [Legedric/ptmagic#499]
Hey there!

Less of an issue and rather a feature request:

Setting single market settings based off of indicators. 

Like: Change trailing_buy / profit based on volatility / BBWIDTH. 

I think people might be able to do some nifty stuff if this could be implemented. 

Any thoughts on that? Possible in the future or won't make it to the list?

**Comment by stevenshizzleh** [comment]
@Fransenson this is neat idea. A lot of times I want to be able to set the conditions based on the behavior of a pair. I can't always characterize the behavior of a pair based on points in time...there could be gaps or it might not be possible to get level of fidelity I need to decide how a pair is acting.

If this were implemented, one of the buy strategies would have to stay the same because we'd have to be able to use it at all times to determine the state of a pair and what we want to do with it.

**Comment by Legedric** [comment]
While I do see some value in this for PTM I stick to the statement I previously made on this GitHub and on Discord about this:
When we implement indicators like RSI, BB, MACD etc. into PTM the step to develop a complete trading bot (making PTM a standalone product on its own) is quite small in terms of effort as pretty much only the trading API to Binance etc. would be missing (some order management around that but you get where I am going).

So I am afraid to say this but it will not happen. The time we would have to put into this (especially supporting this) would be too much for a freetime project.
