### ISSUE TITLE
ERROR ConfigApi - Config could not be loaded from the rest api. Received message: 404

### ISSUE THREAD

**Issue by jojogilpo** [Legedric/ptmagic#565]
I am seeing this error x 3 in the Profit Trailer command window every time that PTMagic attempts to update the settings on Profit Trailer.  PTMagic is otherwise operating properly.  According to this issue posted on the Profit Trailer github, it appears to be a PTMagic issue: https://github.com/taniman/profit-trailer/issues/1917.  Thanks.

**Comment by Legedric** [comment]
The problem is not really a bug but the issue is that you try to load a not existing config, just as it was already said on the PT GitHub.

So yes, PTM does not handle this properly maybe but the fact is that this error occurs because you set a ProfitTrailerDefaultSettingName in you settings.general.json that does not exist in your PT.

**Comment by jojogilpo** [comment]
Yes, that was the issue.  Thanks!
