### ISSUE TITLE
monitor only displays HTML

### ISSUE THREAD

**Issue by michaeltietjen** [Legedric/ptmagic#66]
My monitor is only displaying HTML. I'm guessing I'm missing a file.

**Comment by Legedric** [comment]
Please check if all files are located in your Monitor folder.

There should be several files and folders like:
wwwroot
wwwroot/assets
wwwroot/assets/css
wwwroot/assets/js

and so on

**Comment by krims0n32** [comment]
Still having this issue as well (1.0.2). The files are there. Not using IE.

[ptmagic.txt](https://github.com/Legedric/ptmagic/files/1739539/ptmagic.txt)

**Comment by Legedric** [comment]
Well, something seems to block loading the asset files. What is your browser saying? Like 404 cannot found? Access forbidden?

**Comment by krims0n32** [comment]
404 ! Console is saying net::ERR_ABORTED. When I try a curl http://localhost:5000/assets/js/wow.min.js I also get a 404.

**Comment by Legedric** [comment]
Any CHMOD settings missing for the sub folders that may block this? Sorry, but I can only repeat that I am no Unix expert and that's more like a shot into the blue here :)

**Comment by azenator** [comment]
In the case of wrong file permissions he would get a 403. Why do you start the bot as root in / you should start it as user. What kind of distribution do you have?

**Comment by azenator** [comment]
As I can see, your port 5000 is not open so you can not access the wwwroot. Is your port 5000 already in use or blocked by the firewall?

**Comment by krims0n32** [comment]
Permissions should be OK. All files are world-readable. I am running the app in a container (Docker) which runs as root by default. Also tried running it as a non-privileged user but that doesn't help. Port 5000 is open (wouldn't get a 404 response by the webserver otherwise). The connection refused message you see is because curl tries to use IPv6 first before using IPv4.

Is it possible this has something to do with uppercase/lowercase files? Like the problem with looking for PAIRS.PROPERTIES instead of PAIRS.properties?

**Comment by krims0n32** [comment]
```
# dotnet Monitor/Monitor.dll 
Hosting environment: Production
Content root path: /PTMagic
Now listening on: http://0.0.0.0:5000
Application started. Press Ctrl+C to shut down.
```
Is Content root path set correctly here?

**Comment by krims0n32** [comment]
Also tried running on a different OS (CentOS 7) and no docker but natively, same issue.

I googled a bit (I have 0 dotnet experience), maybe this is useful.

https://peterdaugaardrasmussen.com/2017/10/11/getting-a-404-on-a-image-css-javscript-or-another-static-file/

https://stackoverflow.com/questions/46161382/asp-net-core-2-0-kestrel-not-serving-static-content

https://serverfault.com/questions/260777/why-isnt-iis-serving-my-static-css-js-files

**Comment by krims0n32** [comment]
Progress! It's definitely a path issue. Been playing with strace and found that it is looking for wwwroot in the root directory of PTMagic. (e.g. /PTMagic/wwwroot, not /PTMagic/Monitor/wwwroot). If I create a symlink from /PTMagic/wwwroot to /PTMagic/Monitor/wwwroot, it works!

**Comment by TwixRaider** [comment]
How do you start the monitor? 

`dotnet Monitor/Monitor.dll from the PTMagic folder `

or 

`dotnet Monitor.dll from the PTMagic/Monitor folder`

Does it make a difference? Anyway, thank you for figuring this out!

**Comment by krims0n32** [comment]
dotnet Monitor/Monitor.dll from the PTMagic folder.

dotnet Monitor.dll from the PTMagic/Monitor folder gives an error as it cannot find the settings files in that case.

**Comment by TheMagicDrP** [comment]
Having a similar issue: 
"Magic1 > 2018-05-22 08:49 +00:00: 2018/05/22 08:49:36.190 ERROR - Your Profit Trailer monitor (http://52.151.57.35:9101/) is not available!"

When I load the page manually in the web browser, the link changes from http://52.151.57.35:9101/  I get this error:
 

> This 52.151.57.35 page can’t be found
> No webpage was found for the web address: http://52.151.57.35:9101/52.151.57.35/Login
> HTTP ERROR 404

If I remove the "second" instance of 52.151.57.35, so that the link reads http://52.151.57.35:9101/Login, the page loads without CSS styling and any link that I  inspect shows something like this:
<a href="52.151.57.35/BuyAnalyzer"><i class="fa fa-shopping-cart"></i> Buy Analyzer</a>
hovering over the href shows: 52.151.57.35:9101/52.151.57.35/BuyAnalyzer

Any ideas why the ip is getting repeated in all of the links?  

Thanks, Jon
